# Generated by Django 4.2.2 on 2023-06-26 08:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0002_adress_bookinstance_adress'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='elbook',
            field=models.CharField(help_text='Введите ссылку на скачивание', max_length=300, null=True, verbose_name='Ссылка на скачивание'),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.CharField(help_text='Введите цену', max_length=20, null=True, verbose_name='Цена'),
        ),
        migrations.CreateModel(
            name='ElectronicBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ManyToManyField(help_text='Выберите заказчика книги', null=True, to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
                ('elbook', models.ManyToManyField(help_text='Выберите книги', null=True, to='catalog.book', verbose_name='Книги')),
            ],
        ),
    ]
