# Generated by Django 4.2.2 on 2023-06-26 08:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0003_book_elbook_book_price_electronicbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicbook',
            name='client',
            field=models.ManyToManyField(help_text='Выберите заказчика книги', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
        migrations.AlterField(
            model_name='electronicbook',
            name='elbook',
            field=models.ManyToManyField(help_text='Выберите книги', to='catalog.book', verbose_name='Книги'),
        ),
    ]
