# Generated by Django 4.2.2 on 2023-06-26 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0004_alter_electronicbook_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronicbook',
            name='client',
        ),
        migrations.RemoveField(
            model_name='electronicbook',
            name='elbook',
        ),
        migrations.AddField(
            model_name='electronicbook',
            name='client',
            field=models.ForeignKey(default=1, help_text='Выберите заказчика книги', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electronicbook',
            name='elbook',
            field=models.ForeignKey(default=1, help_text='Выберите книги', on_delete=django.db.models.deletion.CASCADE, to='catalog.book', verbose_name='Книги'),
            preserve_default=False,
        ),
    ]
