# Generated by Django 4.2.2 on 2023-06-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_purchase_delete_electronicbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='elbook',
        ),
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(default=1, upload_to='books/'),
            preserve_default=False,
        ),
    ]
